project:
  type: website
  output-dir: _site/en

website:
  title: "AI Scratchpad (EN)"
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "About Me"
        href: about.qmd
      - text: "Privacy Policy"
        href: privacy.qmd
      - text: "Español"
        href: https://aiscratchpad.com/es
      - text: "Catalan"
        href: https://aiscratchpad.com/cat
  comments:
    giscus:
      repo: januarytabaka/januarytabaka.github.io
      repo-id: "R_kgDOPTiMRA"
      category: "General"
      category-id: "DIC_kwDOPTiMRM4CtgfQ"
      mapping: "pathname"
      reactions-enabled: true
      theme: "preferred_color_scheme"
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    include-in-header: _includes/matomo.html
    security:
      content-security-policy:
        # Allows scripts from your own site and giscus
        script-src:
          - "'self'"
          - "https://giscus.app"
      referrer-policy: "no-referrer"

engine: knitr
knitr:
  opts_chunk: 
    engine.path:
      python: /usr/bin/python3
