project:
  type: website
  output-dir: _site

extensions:
  - quarto-ext/iconify

website:
  title: "AI Scratchpad"
  navbar:
    # This is the new block for the "Back to Portal" link
    left:
      - icon: house-door-fill # A Bootstrap icon for "home"
        href: https://aiscratchpad.com/
        text: "Home"
  page-footer:
    center: 
      - text: "About"
        href: /en/about.html
      - text: "&nbsp; | &nbsp;"
      - text: "Privacy Policy"
        href: /en/privacy.html
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    include-in-header: _includes/matomo.html

engine: knitr
knitr:
  opts_chunk: 
    engine.path:
      python: /usr/bin/python3
