name: Publish Quarto Website

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install R Dependencies
        run: R -e "install.packages('tidymodels')"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install Python Dependencies
        run: pip install jupyter scikit-learn pandas matplotlib seaborn PyYAML

      - name: Render Main Site
        uses: quarto-dev/quarto-actions/render@v2

      - name: Render English Site
        uses: quarto-dev/quarto-actions/render@v2
        with:
          path: en

      - name: Render Spanish Site (Subdirectory)
        uses: quarto-dev/quarto-actions/render@v2
        with:
          path: es

      - name: Render Catalan Site (Subdirectory)
        uses: quarto-dev/quarto-actions/render@v2
        with:
          path: cat

      - name: Create Root Redirect
        run: |
          mkdir -p _site
          echo '<!DOCTYPE html><html><head><meta http-equiv="refresh" content="0; url=/en/" /></head></html>' > _site/index.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4